version: "3.8"
services:
  traefik:
    container_name: traefik
    image: traefik:v2.4
    command:
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.network=web"
      - "--entrypoints.web.address=:80" # Only HTTP
      # - "--entrypoints.websecure.address=:443"
      # - "--certificatesResolvers.letsencrypt.acme.tlsChallenge=true"
      # - "--certificatesResolvers.letsencrypt.acme.email=${email}"
      # - "--certificatesResolvers.letsencrypt.acme.storage=${PATH_ACME}"
      # - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--api.dashboard=true"
      #- "--pilot.token=${token}"
      - "--log.level=DEBUG" # Enable access logging
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /letsencrypt:/letsencrypt
      - /tmp/access.log:/tmp/access.log
    labels:
      - "traefik.enable=true"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=${user}:${key}"
      - "traefik.http.routers.traefik.entrypoints=web" # Use HTTP entrypoint
      # - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.rule=Host(`test-proxy.technoleon.local`)"
      - "traefik.http.routers.traefik.service=api@internal"
      # - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"

  postgreskeycloak:
    container_name: postgreskeycloak
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./tmpdata/pgdatakeycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  # Als je geen RDS database hebt kan je deze gebruiken en DB_URI aanpassen onder technoleon
  technoleondb:
    container_name: technoleondb
    image: postgres:16
    restart: always
    ports:
      - "5433:5433"
    volumes:
      - ./tmpdata/pgdatatechnoleon:/var/lib/postgresql/data
    environment:
      PGPORT: 5433
      POSTGRES_DB: technoleonmain
      POSTGRES_USER: technoleon
      POSTGRES_PASSWORD: password

  keycloak:
    hostname: test-sso.technoleon.local
    image: 511877958163.dkr.ecr.eu-central-1.amazonaws.com/prod:keycloak-latest
    container_name: keycloak
    restart: always
    command:
      - start-dev
    environment:
      KC_DB_URL: "jdbc:postgresql://postgreskeycloak:5432/keycloak"
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_RELATIVE_PATH: '/auth'
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_FRONTEND_URL: http://test-sso.technoleon.local/auth
      KC_HOSTNAME: test-sso.technoleon.local
      PROXY_ADDRESS_FORWARDING: 'true'
    links:
      - postgreskeycloak
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.entrypoints=web" # Use HTTP entrypoint
      - "traefik.http.routers.keycloak.rule=Host(`test-sso.technoleon.local`)"
      # - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"
    ports:
      - "8080:8080"
      - "9990:9990"

  technoleon:
    container_name: technoleon
    image: 511877958163.dkr.ecr.eu-central-1.amazonaws.com/prod:technoleon-latest
    links:
      - traefik
      - keycloak
      - technoleondb
    environment:
      DATA_DIR: /technoleon/data
      MIGRATIONS_DIR: platform/migrations
      FLASK_APP: platform/wsgi.py
      KEYCLOAK_INTERNAL_URL: http://keycloak:8080/auth
      KEYCLOAK_FRONTEND_URL: http://test-sso.technoleon.local/auth
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_REALM: DEV
      KEYCLOAK_CLIENT_NAME: TECHNOLEON
      KEYCLOAK_URL: http://test-sso.technoleon.local
      APP_URL: http://test-technoleon.local
      SECRET_KEY: koekjes123
      #FCM_KEY: ${FCM_KEY}
      #DB_URI: postgresql+psycopg2://technoleon:password@technoleondb:5433/technoleonmain
      DB_URI: postgresql+psycopg2://postgres:Jn5Pw7XYb%26%24g%244@technoleon.cnllhjzcpui9.eu-central-1.rds.amazonaws.com/technoleon
      #MAIL_PORT: 587
      #MAIL_PASSWORD: ${MAIL_PASSWORD}
      #MAIL_USE_TLS: true
      #MAIL_USERNAME: ${MAIL_user}
      #MAIL_SERVER: ${MAIL_SERVER}
      KEYCLOAK_REALM_USER: test
      KEYCLOAK_REALM_EMAIL: test@test.nl
      KEYCLOAK_REALM_PASSWORD: password
      CRYPTOGRAPHY_KEY: hg6DTM6L2rKdm4Wfpc0yAZNGdQsvLuv9wmbHsOr_vjA=
    volumes:
      - ./platform:/app/platform
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.technoleon.entrypoints=web" # Use HTTP entrypoint
      # - "traefik.http.routers.technoleon.tls.certresolver=letsencrypt"
      - "traefik.http.services.techoleon.loadbalancer.server.port=5000"
      - "traefik.http.routers.technoleon.rule=Host(`test-technoleon.local`)"